/*
 * This file was generated by the Gradle 'init' task.
 */

import com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar;

plugins {
    java
    id("com.github.johnrengelman.shadow") version "7.1.0"
}

repositories {
    mavenLocal()
    maven("https://jitpack.io")
    maven("https://rayzr.dev/repo/")
    maven("https://hub.spigotmc.org/nexus/content/repositories/snapshots/")
    maven("https://repo.extendedclip.com/content/repositories/placeholderapi/")
}

dependencies {
    implementation("me.rayzr522:jsonmessage:1.3.0")
    implementation("com.github.cryptomorin:XSeries:8.4.0")

    compileOnly("org.spigotmc:spigot-api:1.16.3-R0.1-SNAPSHOT")
    compileOnly("me.clip:placeholderapi:2.10.10")
}

group = "com.octanna"
version = "1.3.8"
description = "SpigotPluginLib"

tasks.withType<ShadowJar> {
    relocate("de.tr7zw", "${project.group}.lib.nbt")
    relocate("me.rayzr522.jsonmessage", "${project.group}.lib.general")
    relocate("com.cryptomorin.xseries", "${project.group}.lib.xseries")
}

tasks.withType<JavaCompile> {
    options.encoding = "UTF-8"
}